# Generated by Django 3.1.5 on 2021-01-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0002_auto_20210112_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='tipo',
            field=models.BooleanField(choices=[(True, 'Filme'), (False, 'Serie')], default=True),
        ),
    ]
