# Generated by Django 3.1.5 on 2021-01-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0003_auto_20210112_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programa',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
