# Generated by Django 3.1.5 on 2021-01-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0005_auto_20210112_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='updated_at',
        ),
    ]
