# Generated by Django 3.1.5 on 2021-01-13 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluraflix', '0007_auto_20210113_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='programa',
            name='updated_at',
        ),
    ]
